package Exercicios;

//ESSA ANOTAÇÃO DEFINE QUE A INTERFACE TERÁ UM MÉTODO QUE PODERÁ TER PROGRAMAÇÃO FUNCIONAL OU USO DA LAMBA, ENTRETANTO, TODA INTERFACE SÓ PODE TER UM METODO NÃO IMPLEMENTADO, NÃO PODE TER 2 METODOS SEM IMPLEMENTAÇÕES
@FunctionalInterface
public interface Inteiro {
	
	//ESSE É O METODO QUE VAI TER UMA LAMBA NA SUA IMPLEMENTAÇÃO, ELE TEM UM ARRAY DE INTEIROS COMO PARAMETRO E RETORNA UM INTEIRO
	int retornaResultado(int[] array);
	

}
